name: CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Bundle dependencie
      run: bundle install
      
    - name: Build and run tests
      run: bundle exec fastlane build_and_test
